// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBaNdTCddgyh4GCJf8rWCZbJ7xOxpp7cr4',
    appId: '1:503125186105:web:cee463611d7780e243dfe8',
    messagingSenderId: '503125186105',
    projectId: 'todo-c8-ec3b4',
    authDomain: 'todo-c8-ec3b4.firebaseapp.com',
    storageBucket: 'todo-c8-ec3b4.appspot.com',
    measurementId: 'G-HSTPBR401H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH0HiT3m7N4jyfR7Pt_r5kw78ADHhYNC0',
    appId: '1:503125186105:android:62219654e9084c0943dfe8',
    messagingSenderId: '503125186105',
    projectId: 'todo-c8-ec3b4',
    storageBucket: 'todo-c8-ec3b4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCzHk-xcA0ResZzoi6LSD7oKGDfbza1PWo',
    appId: '1:503125186105:ios:87ce4a7a3803ecbc43dfe8',
    messagingSenderId: '503125186105',
    projectId: 'todo-c8-ec3b4',
    storageBucket: 'todo-c8-ec3b4.appspot.com',
    iosBundleId: 'com.example.todoC8',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCzHk-xcA0ResZzoi6LSD7oKGDfbza1PWo',
    appId: '1:503125186105:ios:87ce4a7a3803ecbc43dfe8',
    messagingSenderId: '503125186105',
    projectId: 'todo-c8-ec3b4',
    storageBucket: 'todo-c8-ec3b4.appspot.com',
    iosBundleId: 'com.example.todoC8',
  );
}
